---
title: "The theory of Streams"
description: |
  Streams are the categorical dual to lists - they are the terminal coalgebra of the same functor that lists are algebras of.
author:
  - name: Rahul Chhabra
    url: https://rahulc29.github.io/
date: 2023-07-18
output:
  distill::distill_article:
    self_contained: false
---

# Ceremonial imports :

<pre class="Agda"><a id="31" class="Symbol">{-#</a> <a id="35" class="Keyword">OPTIONS</a> <a id="43" class="Pragma">--cubical</a> <a id="53" class="Pragma">--guardedness</a> <a id="67" class="Symbol">#-}</a>
<a id="71" class="Keyword">open</a> <a id="76" class="Keyword">import</a> <a id="83" href="Cubical.Core.Everything.html" class="Module">Cubical.Core.Everything</a>
<a id="107" class="Keyword">open</a> <a id="112" class="Keyword">import</a> <a id="119" href="Cubical.Foundations.Prelude.html" class="Module">Cubical.Foundations.Prelude</a>
<a id="147" class="Keyword">open</a> <a id="152" class="Keyword">import</a> <a id="159" href="Cubical.Data.Maybe.html" class="Module">Cubical.Data.Maybe</a>
<a id="178" class="Keyword">open</a> <a id="183" class="Keyword">import</a> <a id="190" href="Cubical.Data.Sigma.html" class="Module">Cubical.Data.Sigma</a>
</pre>
Let us define streams (they are the final coalgebra of a certain functor).

<pre class="Agda"><a id="298" class="Keyword">record</a> <a id="Stream"></a><a id="305" href="Streams.html#305" class="Record">Stream</a> <a id="312" class="Symbol">(</a><a id="313" href="Streams.html#313" class="Bound">A</a> <a id="315" class="Symbol">:</a> <a id="317" href="Agda.Primitive.html#320" class="Primitive">Set</a><a id="320" class="Symbol">)</a> <a id="322" class="Symbol">:</a> <a id="324" href="Agda.Primitive.html#320" class="Primitive">Set</a> <a id="328" class="Keyword">where</a>
  <a id="336" class="Keyword">coinductive</a>
  <a id="350" class="Keyword">field</a>
    <a id="Stream.head"></a><a id="360" href="Streams.html#360" class="Field">head</a> <a id="365" class="Symbol">:</a> <a id="367" href="Streams.html#313" class="Bound">A</a>
    <a id="Stream.tail"></a><a id="373" href="Streams.html#373" class="Field">tail</a> <a id="378" class="Symbol">:</a> <a id="380" href="Streams.html#305" class="Record">Stream</a> <a id="387" href="Streams.html#313" class="Bound">A</a>
<a id="389" class="Keyword">open</a> <a id="394" href="Streams.html#305" class="Module">Stream</a>
</pre>
Let us define the function that extracts even indexed elements.

<pre class="Agda"><a id="evens"></a><a id="479" href="Streams.html#479" class="Function">evens</a> <a id="485" class="Symbol">:</a> <a id="487" class="Symbol">∀</a> <a id="489" class="Symbol">{</a><a id="490" href="Streams.html#490" class="Bound">A</a> <a id="492" class="Symbol">:</a> <a id="494" href="Agda.Primitive.html#320" class="Primitive">Set</a><a id="497" class="Symbol">}</a> <a id="499" class="Symbol">→</a> <a id="501" href="Streams.html#305" class="Record">Stream</a> <a id="508" href="Streams.html#490" class="Bound">A</a> <a id="510" class="Symbol">→</a> <a id="512" href="Streams.html#305" class="Record">Stream</a> <a id="519" href="Streams.html#490" class="Bound">A</a>
<a id="521" href="Streams.html#360" class="Field">head</a> <a id="526" class="Symbol">(</a><a id="527" href="Streams.html#479" class="Function">evens</a> <a id="533" href="Streams.html#533" class="Bound">x</a><a id="534" class="Symbol">)</a> <a id="536" class="Symbol">=</a> <a id="538" href="Streams.html#360" class="Field">head</a> <a id="543" href="Streams.html#533" class="Bound">x</a>
<a id="545" href="Streams.html#373" class="Field">tail</a> <a id="550" class="Symbol">(</a><a id="551" href="Streams.html#479" class="Function">evens</a> <a id="557" href="Streams.html#557" class="Bound">x</a><a id="558" class="Symbol">)</a> <a id="560" class="Symbol">=</a> <a id="562" href="Streams.html#479" class="Function">evens</a> <a id="568" class="Symbol">(</a><a id="569" href="Streams.html#373" class="Field">tail</a> <a id="574" class="Symbol">(</a><a id="575" href="Streams.html#373" class="Field">tail</a> <a id="580" href="Streams.html#557" class="Bound">x</a><a id="581" class="Symbol">))</a>
</pre>
Similary, we construct the function that extracts odd indexed elements.

<pre class="Agda"><a id="odds"></a><a id="670" href="Streams.html#670" class="Function">odds</a> <a id="675" class="Symbol">:</a> <a id="677" class="Symbol">∀</a> <a id="679" class="Symbol">{</a><a id="680" href="Streams.html#680" class="Bound">A</a> <a id="682" class="Symbol">:</a> <a id="684" href="Agda.Primitive.html#320" class="Primitive">Set</a><a id="687" class="Symbol">}</a> <a id="689" class="Symbol">→</a> <a id="691" href="Streams.html#305" class="Record">Stream</a> <a id="698" href="Streams.html#680" class="Bound">A</a> <a id="700" class="Symbol">→</a> <a id="702" href="Streams.html#305" class="Record">Stream</a> <a id="709" href="Streams.html#680" class="Bound">A</a>
<a id="711" href="Streams.html#360" class="Field">head</a> <a id="716" class="Symbol">(</a><a id="717" href="Streams.html#670" class="Function">odds</a> <a id="722" href="Streams.html#722" class="Bound">x</a><a id="723" class="Symbol">)</a> <a id="725" class="Symbol">=</a> <a id="727" href="Streams.html#360" class="Field">head</a> <a id="732" class="Symbol">(</a><a id="733" href="Streams.html#722" class="Bound">x</a> <a id="735" class="Symbol">.</a><a id="736" href="Streams.html#373" class="Field">tail</a><a id="740" class="Symbol">)</a>
<a id="742" href="Streams.html#373" class="Field">tail</a> <a id="747" class="Symbol">(</a><a id="748" href="Streams.html#670" class="Function">odds</a> <a id="753" href="Streams.html#753" class="Bound">x</a><a id="754" class="Symbol">)</a> <a id="756" class="Symbol">=</a> <a id="758" href="Streams.html#670" class="Function">odds</a> <a id="763" class="Symbol">(</a><a id="764" href="Streams.html#373" class="Field">tail</a> <a id="769" class="Symbol">(</a><a id="770" href="Streams.html#373" class="Field">tail</a> <a id="775" href="Streams.html#753" class="Bound">x</a><a id="776" class="Symbol">))</a>
</pre>
We now define bisimulation relations for streams

<pre class="Agda"><a id="842" class="Keyword">record</a> <a id="_≈_"></a><a id="849" href="Streams.html#849" class="Record Operator">_≈_</a> <a id="853" class="Symbol">{</a><a id="854" href="Streams.html#854" class="Bound">A</a> <a id="856" class="Symbol">:</a> <a id="858" href="Agda.Primitive.html#320" class="Primitive">Set</a><a id="861" class="Symbol">}</a> <a id="863" class="Symbol">(</a><a id="864" href="Streams.html#864" class="Bound">x</a> <a id="866" href="Streams.html#866" class="Bound">y</a> <a id="868" class="Symbol">:</a> <a id="870" href="Streams.html#305" class="Record">Stream</a> <a id="877" href="Streams.html#854" class="Bound">A</a><a id="878" class="Symbol">)</a> <a id="880" class="Symbol">:</a> <a id="882" href="Agda.Primitive.html#320" class="Primitive">Set</a> <a id="886" class="Keyword">where</a>
  <a id="894" class="Keyword">coinductive</a>
  <a id="908" class="Keyword">field</a>
    <a id="_≈_.head-≡"></a><a id="918" href="Streams.html#918" class="Field">head-≡</a> <a id="925" class="Symbol">:</a> <a id="927" href="Streams.html#360" class="Field">head</a> <a id="932" href="Streams.html#864" class="Bound">x</a> <a id="934" href="Agda.Builtin.Cubical.Path.html#272" class="Function Operator">≡</a> <a id="936" href="Streams.html#360" class="Field">head</a> <a id="941" href="Streams.html#866" class="Bound">y</a>
    <a id="_≈_.tail-≈"></a><a id="947" href="Streams.html#947" class="Field">tail-≈</a> <a id="954" class="Symbol">:</a> <a id="956" href="Streams.html#373" class="Field">tail</a> <a id="961" href="Streams.html#864" class="Bound">x</a> <a id="963" href="Streams.html#849" class="Record Operator">≈</a> <a id="965" href="Streams.html#373" class="Field">tail</a> <a id="970" href="Streams.html#866" class="Bound">y</a>
<a id="972" class="Keyword">open</a> <a id="977" href="Streams.html#849" class="Module Operator">_≈_</a>
</pre>
Okay, now we have a proof of coinductive extensionality!

<pre class="Agda"><a id="≈→≡"></a><a id="1052" href="Streams.html#1052" class="Function">≈→≡</a> <a id="1056" class="Symbol">:</a> <a id="1058" class="Symbol">∀</a> <a id="1060" class="Symbol">{</a><a id="1061" href="Streams.html#1061" class="Bound">A</a> <a id="1063" class="Symbol">:</a> <a id="1065" href="Agda.Primitive.html#320" class="Primitive">Set</a><a id="1068" class="Symbol">}</a> <a id="1070" class="Symbol">→</a> <a id="1072" class="Symbol">∀</a> <a id="1074" class="Symbol">{</a><a id="1075" href="Streams.html#1075" class="Bound">xs</a> <a id="1078" href="Streams.html#1078" class="Bound">ys</a> <a id="1081" class="Symbol">:</a> <a id="1083" href="Streams.html#305" class="Record">Stream</a> <a id="1090" href="Streams.html#1061" class="Bound">A</a><a id="1091" class="Symbol">}</a> <a id="1093" class="Symbol">→</a> <a id="1095" href="Streams.html#1075" class="Bound">xs</a> <a id="1098" href="Streams.html#849" class="Record Operator">≈</a> <a id="1100" href="Streams.html#1078" class="Bound">ys</a> <a id="1103" class="Symbol">→</a> <a id="1105" href="Streams.html#1075" class="Bound">xs</a> <a id="1108" href="Agda.Builtin.Cubical.Path.html#272" class="Function Operator">≡</a> <a id="1110" href="Streams.html#1078" class="Bound">ys</a>
<a id="1113" href="Streams.html#360" class="Field">head</a> <a id="1118" class="Symbol">(</a><a id="1119" href="Streams.html#1052" class="Function">≈→≡</a> <a id="1123" href="Streams.html#1123" class="Bound">xs≈ys</a> <a id="1129" href="Streams.html#1129" class="Bound">i</a><a id="1130" class="Symbol">)</a> <a id="1132" class="Symbol">=</a> <a id="1134" class="Symbol">(</a><a id="1135" href="Streams.html#918" class="Field">head-≡</a> <a id="1142" href="Streams.html#1123" class="Bound">xs≈ys</a><a id="1147" class="Symbol">)</a> <a id="1149" href="Streams.html#1129" class="Bound">i</a>
<a id="1151" href="Streams.html#373" class="Field">tail</a> <a id="1156" class="Symbol">(</a><a id="1157" href="Streams.html#1052" class="Function">≈→≡</a> <a id="1161" href="Streams.html#1161" class="Bound">xs≈ys</a> <a id="1167" href="Streams.html#1167" class="Bound">i</a><a id="1168" class="Symbol">)</a> <a id="1170" class="Symbol">=</a> <a id="1172" href="Streams.html#1052" class="Function">≈→≡</a> <a id="1176" class="Symbol">(</a><a id="1177" href="Streams.html#947" class="Field">tail-≈</a> <a id="1184" href="Streams.html#1161" class="Bound">xs≈ys</a><a id="1189" class="Symbol">)</a> <a id="1191" href="Streams.html#1167" class="Bound">i</a>

<a id="≡→≈"></a><a id="1194" href="Streams.html#1194" class="Function">≡→≈</a> <a id="1198" class="Symbol">:</a> <a id="1200" class="Symbol">∀</a> <a id="1202" class="Symbol">{</a><a id="1203" href="Streams.html#1203" class="Bound">A</a> <a id="1205" class="Symbol">:</a> <a id="1207" href="Agda.Primitive.html#320" class="Primitive">Set</a><a id="1210" class="Symbol">}</a> <a id="1212" class="Symbol">→</a> <a id="1214" class="Symbol">∀</a> <a id="1216" class="Symbol">{</a><a id="1217" href="Streams.html#1217" class="Bound">xs</a> <a id="1220" href="Streams.html#1220" class="Bound">ys</a> <a id="1223" class="Symbol">:</a> <a id="1225" href="Streams.html#305" class="Record">Stream</a> <a id="1232" href="Streams.html#1203" class="Bound">A</a><a id="1233" class="Symbol">}</a> <a id="1235" class="Symbol">→</a> <a id="1237" href="Streams.html#1217" class="Bound">xs</a> <a id="1240" href="Agda.Builtin.Cubical.Path.html#272" class="Function Operator">≡</a> <a id="1242" href="Streams.html#1220" class="Bound">ys</a> <a id="1245" class="Symbol">→</a> <a id="1247" href="Streams.html#1217" class="Bound">xs</a> <a id="1250" href="Streams.html#849" class="Record Operator">≈</a> <a id="1252" href="Streams.html#1220" class="Bound">ys</a>
<a id="1255" href="Streams.html#918" class="Field">head-≡</a> <a id="1262" class="Symbol">(</a><a id="1263" href="Streams.html#1194" class="Function">≡→≈</a> <a id="1267" href="Streams.html#1267" class="Bound">xs≡ys</a><a id="1272" class="Symbol">)</a> <a id="1274" class="Symbol">=</a> <a id="1276" class="Symbol">λ</a> <a id="1278" href="Streams.html#1278" class="Bound">i</a> <a id="1280" class="Symbol">→</a> <a id="1282" href="Streams.html#360" class="Field">head</a> <a id="1287" class="Symbol">(</a><a id="1288" href="Streams.html#1267" class="Bound">xs≡ys</a> <a id="1294" href="Streams.html#1278" class="Bound">i</a><a id="1295" class="Symbol">)</a>
<a id="1297" href="Streams.html#947" class="Field">tail-≈</a> <a id="1304" class="Symbol">(</a><a id="1305" href="Streams.html#1194" class="Function">≡→≈</a> <a id="1309" href="Streams.html#1309" class="Bound">xs≡ys</a><a id="1314" class="Symbol">)</a> <a id="1316" class="Symbol">=</a> <a id="1318" href="Streams.html#1194" class="Function">≡→≈</a> <a id="1322" class="Symbol">(λ</a> <a id="1325" href="Streams.html#1325" class="Bound">i</a> <a id="1327" class="Symbol">→</a> <a id="1329" href="Streams.html#373" class="Field">tail</a> <a id="1334" class="Symbol">(</a><a id="1335" href="Streams.html#1309" class="Bound">xs≡ys</a> <a id="1341" href="Streams.html#1325" class="Bound">i</a><a id="1342" class="Symbol">))</a>
</pre>
Now we must show our equation.

<pre class="Agda"><a id="1390" class="Symbol">{-#</a> <a id="1394" class="Keyword">TERMINATING</a> <a id="1406" class="Symbol">#-}</a>
<a id="evens∙tail≈odds"></a><a id="1410" href="Streams.html#1410" class="Function">evens∙tail≈odds</a> <a id="1426" class="Symbol">:</a> <a id="1428" class="Symbol">∀</a> <a id="1430" class="Symbol">{</a><a id="1431" href="Streams.html#1431" class="Bound">A</a> <a id="1433" class="Symbol">:</a> <a id="1435" href="Agda.Primitive.html#320" class="Primitive">Set</a><a id="1438" class="Symbol">}</a> <a id="1440" class="Symbol">→</a> <a id="1442" class="Symbol">∀</a> <a id="1444" class="Symbol">(</a><a id="1445" href="Streams.html#1445" class="Bound">xs</a> <a id="1448" class="Symbol">:</a> <a id="1450" href="Streams.html#305" class="Record">Stream</a> <a id="1457" href="Streams.html#1431" class="Bound">A</a><a id="1458" class="Symbol">)</a> <a id="1460" class="Symbol">→</a> <a id="1462" href="Streams.html#479" class="Function">evens</a> <a id="1468" class="Symbol">(</a><a id="1469" href="Streams.html#373" class="Field">tail</a> <a id="1474" href="Streams.html#1445" class="Bound">xs</a><a id="1476" class="Symbol">)</a> <a id="1478" href="Streams.html#849" class="Record Operator">≈</a> <a id="1480" href="Streams.html#670" class="Function">odds</a> <a id="1485" href="Streams.html#1445" class="Bound">xs</a>
<a id="1488" href="Streams.html#918" class="Field">head-≡</a> <a id="1495" class="Symbol">(</a><a id="1496" href="Streams.html#1410" class="Function">evens∙tail≈odds</a> <a id="1512" href="Streams.html#1512" class="Bound">xs</a><a id="1514" class="Symbol">)</a> <a id="1516" class="Symbol">=</a> <a id="1518" href="Cubical.Foundations.Prelude.html#915" class="Function">refl</a>
<a id="1523" href="Streams.html#947" class="Field">tail-≈</a> <a id="1530" class="Symbol">(</a><a id="1531" href="Streams.html#1410" class="Function">evens∙tail≈odds</a> <a id="1547" href="Streams.html#1547" class="Bound">xs</a><a id="1549" class="Symbol">)</a> <a id="1551" class="Symbol">=</a> <a id="1553" href="Streams.html#1194" class="Function">≡→≈</a> <a id="1557" class="Symbol">((</a><a id="1559" href="Streams.html#1052" class="Function">≈→≡</a> <a id="1563" class="Symbol">(</a><a id="1564" href="Streams.html#1410" class="Function">evens∙tail≈odds</a> <a id="1580" class="Symbol">(</a><a id="1581" href="Streams.html#373" class="Field">tail</a> <a id="1586" class="Symbol">(</a><a id="1587" href="Streams.html#373" class="Field">tail</a> <a id="1592" href="Streams.html#1547" class="Bound">xs</a><a id="1594" class="Symbol">))))</a> <a id="1599" href="Cubical.Foundations.Prelude.html#4447" class="Function Operator">∙</a> <a id="1601" class="Symbol">(</a><a id="1602" href="Cubical.Foundations.Prelude.html#968" class="Function">sym</a> <a id="1606" href="Cubical.Foundations.Prelude.html#915" class="Function">refl</a><a id="1610" class="Symbol">))</a>

<a id="evens∙tail≡odds"></a><a id="1614" href="Streams.html#1614" class="Function">evens∙tail≡odds</a> <a id="1630" class="Symbol">:</a> <a id="1632" class="Symbol">∀</a> <a id="1634" class="Symbol">{</a><a id="1635" href="Streams.html#1635" class="Bound">A</a> <a id="1637" class="Symbol">:</a> <a id="1639" href="Agda.Primitive.html#320" class="Primitive">Set</a><a id="1642" class="Symbol">}</a> <a id="1644" class="Symbol">→</a> <a id="1646" class="Symbol">∀</a> <a id="1648" class="Symbol">(</a><a id="1649" href="Streams.html#1649" class="Bound">xs</a> <a id="1652" class="Symbol">:</a> <a id="1654" href="Streams.html#305" class="Record">Stream</a> <a id="1661" href="Streams.html#1635" class="Bound">A</a><a id="1662" class="Symbol">)</a> <a id="1664" class="Symbol">→</a> <a id="1666" href="Streams.html#479" class="Function">evens</a> <a id="1672" class="Symbol">(</a><a id="1673" href="Streams.html#373" class="Field">tail</a> <a id="1678" href="Streams.html#1649" class="Bound">xs</a><a id="1680" class="Symbol">)</a> <a id="1682" href="Agda.Builtin.Cubical.Path.html#272" class="Function Operator">≡</a> <a id="1684" href="Streams.html#670" class="Function">odds</a> <a id="1689" href="Streams.html#1649" class="Bound">xs</a>
<a id="1692" href="Streams.html#1614" class="Function">evens∙tail≡odds</a> <a id="1708" href="Streams.html#1708" class="Bound">xs</a> <a id="1711" class="Symbol">=</a> <a id="1713" href="Streams.html#1052" class="Function">≈→≡</a> <a id="1717" class="Symbol">(</a><a id="1718" href="Streams.html#1410" class="Function">evens∙tail≈odds</a> <a id="1734" href="Streams.html#1708" class="Bound">xs</a><a id="1736" class="Symbol">)</a>
</pre>
Now let us define the merge operation for streams. The merge operation takes the first element from the left stream and the second element from the second stream.

<pre class="Agda"><a id="merge"></a><a id="1915" href="Streams.html#1915" class="Function">merge</a> <a id="1921" class="Symbol">:</a> <a id="1923" class="Symbol">∀</a> <a id="1925" class="Symbol">{</a><a id="1926" href="Streams.html#1926" class="Bound">A</a> <a id="1928" class="Symbol">:</a> <a id="1930" href="Agda.Primitive.html#320" class="Primitive">Set</a><a id="1933" class="Symbol">}</a> <a id="1935" class="Symbol">→</a> <a id="1937" href="Streams.html#305" class="Record">Stream</a> <a id="1944" href="Streams.html#1926" class="Bound">A</a> <a id="1946" class="Symbol">→</a> <a id="1948" href="Streams.html#305" class="Record">Stream</a> <a id="1955" href="Streams.html#1926" class="Bound">A</a> <a id="1957" class="Symbol">→</a> <a id="1959" href="Streams.html#305" class="Record">Stream</a> <a id="1966" href="Streams.html#1926" class="Bound">A</a>
<a id="1968" href="Streams.html#360" class="Field">head</a> <a id="1973" class="Symbol">(</a><a id="1974" href="Streams.html#1915" class="Function">merge</a> <a id="1980" href="Streams.html#1980" class="Bound">x</a> <a id="1982" href="Streams.html#1982" class="Bound">y</a><a id="1983" class="Symbol">)</a> <a id="1985" class="Symbol">=</a> <a id="1987" href="Streams.html#1980" class="Bound">x</a> <a id="1989" class="Symbol">.</a><a id="1990" href="Streams.html#360" class="Field">head</a>
<a id="1995" href="Streams.html#373" class="Field">tail</a> <a id="2000" class="Symbol">(</a><a id="2001" href="Streams.html#1915" class="Function">merge</a> <a id="2007" href="Streams.html#2007" class="Bound">x</a> <a id="2009" href="Streams.html#2009" class="Bound">y</a><a id="2010" class="Symbol">)</a> <a id="2012" class="Symbol">=</a> <a id="2014" href="Streams.html#1915" class="Function">merge</a> <a id="2020" href="Streams.html#2009" class="Bound">y</a> <a id="2022" class="Symbol">(</a><a id="2023" href="Streams.html#2007" class="Bound">x</a> <a id="2025" class="Symbol">.</a><a id="2026" href="Streams.html#373" class="Field">tail</a><a id="2030" class="Symbol">)</a>
</pre>

## The Even Odd Merger Theorem

The time has come for us to make our biggest theorem yet.

For the proof, we need a simple lemma :

We will start with the bisimulation lemma and the actual proof would be a simple application of extensionality.

<pre class="Agda"><a id="2290" class="Comment">-- merge-evens-odds-id : ∀ {A : Set} → ∀ (x : Stream A) → merge (evens x) (odds x) ≈ x</a>
<a id="2377" class="Comment">-- head-≡ (merge-evens-odds-id x) = refl</a>
<a id="2418" class="Comment">-- tail-≈ (merge-evens-odds-id x) = ≡→≈ {!? ∙∙ (merge-evens-odds-id (tail x)) ∙∙ refl!}</a>
</pre>

## Predicates and Temporal Logic

We define a predicate as a family of types indexed by the state space.
