---
title: "Exploring "
description: |
      Streams are the categorical dual to lists - they are the terminal coalgebra of the same functor that lists are algebras of.
author:
  - name: Rahul Chhabra
    url: https://rahulc29.github.io/
date: 2023-07-18
categories:
output:
  distill::distill_article:
    toc: true
    self_contained: true
---
# Ceremonial imports :

<pre class="Agda"><a id="31" class="Symbol">{-#</a> <a id="35" class="Keyword">OPTIONS</a> <a id="43" class="Pragma">--cubical</a> <a id="53" class="Pragma">--guardedness</a> <a id="67" class="Symbol">#-}</a>
<a id="71" class="Keyword">open</a> <a id="76" class="Keyword">import</a> <a id="83" href="Cubical.Core.Everything.html" class="Module">Cubical.Core.Everything</a>
</pre>
Let us define streams (they are the final coalgebra of a certain functor).

<pre class="Agda"><a id="196" class="Keyword">record</a> <a id="Stream"></a><a id="203" href="Streams.html#203" class="Record">Stream</a> <a id="210" class="Symbol">(</a><a id="211" href="Streams.html#211" class="Bound">A</a> <a id="213" class="Symbol">:</a> <a id="215" href="Agda.Primitive.html#320" class="Primitive">Set</a><a id="218" class="Symbol">)</a> <a id="220" class="Symbol">:</a> <a id="222" href="Agda.Primitive.html#320" class="Primitive">Set</a> <a id="226" class="Keyword">where</a>
  <a id="234" class="Keyword">coinductive</a>
  <a id="248" class="Keyword">field</a>
    <a id="Stream.head"></a><a id="258" href="Streams.html#258" class="Field">head</a> <a id="263" class="Symbol">:</a> <a id="265" href="Streams.html#211" class="Bound">A</a>
    <a id="Stream.tail"></a><a id="271" href="Streams.html#271" class="Field">tail</a> <a id="276" class="Symbol">:</a> <a id="278" href="Streams.html#203" class="Record">Stream</a> <a id="285" href="Streams.html#211" class="Bound">A</a>
<a id="287" class="Keyword">open</a> <a id="292" href="Streams.html#203" class="Module">Stream</a>
</pre>
Let us define the function that extracts even indexed elements.

<pre class="Agda"><a id="evens"></a><a id="377" href="Streams.html#377" class="Function">evens</a> <a id="383" class="Symbol">:</a> <a id="385" class="Symbol">∀</a> <a id="387" class="Symbol">{</a><a id="388" href="Streams.html#388" class="Bound">A</a> <a id="390" class="Symbol">:</a> <a id="392" href="Agda.Primitive.html#320" class="Primitive">Set</a><a id="395" class="Symbol">}</a> <a id="397" class="Symbol">→</a> <a id="399" href="Streams.html#203" class="Record">Stream</a> <a id="406" href="Streams.html#388" class="Bound">A</a> <a id="408" class="Symbol">→</a> <a id="410" href="Streams.html#203" class="Record">Stream</a> <a id="417" href="Streams.html#388" class="Bound">A</a>
<a id="419" href="Streams.html#258" class="Field">head</a> <a id="424" class="Symbol">(</a><a id="425" href="Streams.html#377" class="Function">evens</a> <a id="431" href="Streams.html#431" class="Bound">x</a><a id="432" class="Symbol">)</a> <a id="434" class="Symbol">=</a> <a id="436" href="Streams.html#258" class="Field">head</a> <a id="441" href="Streams.html#431" class="Bound">x</a>
<a id="443" href="Streams.html#271" class="Field">tail</a> <a id="448" class="Symbol">(</a><a id="449" href="Streams.html#377" class="Function">evens</a> <a id="455" href="Streams.html#455" class="Bound">x</a><a id="456" class="Symbol">)</a> <a id="458" class="Symbol">=</a> <a id="460" href="Streams.html#271" class="Field">tail</a> <a id="465" class="Symbol">(</a><a id="466" href="Streams.html#271" class="Field">tail</a> <a id="471" href="Streams.html#455" class="Bound">x</a><a id="472" class="Symbol">)</a>
</pre>
Similary, we construct the function that extracts odd indexed elements.

<pre class="Agda"><a id="odds"></a><a id="560" href="Streams.html#560" class="Function">odds</a> <a id="565" class="Symbol">:</a> <a id="567" class="Symbol">∀</a> <a id="569" class="Symbol">{</a><a id="570" href="Streams.html#570" class="Bound">A</a> <a id="572" class="Symbol">:</a> <a id="574" href="Agda.Primitive.html#320" class="Primitive">Set</a><a id="577" class="Symbol">}</a> <a id="579" class="Symbol">→</a> <a id="581" href="Streams.html#203" class="Record">Stream</a> <a id="588" href="Streams.html#570" class="Bound">A</a> <a id="590" class="Symbol">→</a> <a id="592" href="Streams.html#203" class="Record">Stream</a> <a id="599" href="Streams.html#570" class="Bound">A</a>
<a id="601" href="Streams.html#258" class="Field">head</a> <a id="606" class="Symbol">(</a><a id="607" href="Streams.html#560" class="Function">odds</a> <a id="612" href="Streams.html#612" class="Bound">x</a><a id="613" class="Symbol">)</a> <a id="615" class="Symbol">=</a> <a id="617" href="Streams.html#258" class="Field">head</a> <a id="622" class="Symbol">(</a><a id="623" href="Streams.html#612" class="Bound">x</a> <a id="625" class="Symbol">.</a><a id="626" href="Streams.html#271" class="Field">tail</a><a id="630" class="Symbol">)</a>
<a id="632" href="Streams.html#271" class="Field">tail</a> <a id="637" class="Symbol">(</a><a id="638" href="Streams.html#560" class="Function">odds</a> <a id="643" href="Streams.html#643" class="Bound">x</a><a id="644" class="Symbol">)</a> <a id="646" class="Symbol">=</a> <a id="648" href="Streams.html#271" class="Field">tail</a> <a id="653" class="Symbol">(</a><a id="654" href="Streams.html#271" class="Field">tail</a> <a id="659" class="Symbol">(</a><a id="660" href="Streams.html#271" class="Field">tail</a> <a id="665" href="Streams.html#643" class="Bound">x</a><a id="666" class="Symbol">))</a>
</pre>

# Bisimulation

We now define bisimulation relations for streams

<pre class="Agda"><a id="732" class="Keyword">record</a> <a id="_≈_"></a><a id="739" href="Streams.html#739" class="Record Operator">_≈_</a> <a id="743" class="Symbol">{</a><a id="744" href="Streams.html#744" class="Bound">A</a> <a id="746" class="Symbol">:</a> <a id="748" href="Agda.Primitive.html#320" class="Primitive">Set</a><a id="751" class="Symbol">}</a> <a id="753" class="Symbol">(</a><a id="754" href="Streams.html#754" class="Bound">x</a> <a id="756" href="Streams.html#756" class="Bound">y</a> <a id="758" class="Symbol">:</a> <a id="760" href="Streams.html#203" class="Record">Stream</a> <a id="767" href="Streams.html#744" class="Bound">A</a><a id="768" class="Symbol">)</a> <a id="770" class="Symbol">:</a> <a id="772" href="Agda.Primitive.html#320" class="Primitive">Set</a> <a id="776" class="Keyword">where</a>
  <a id="784" class="Keyword">coinductive</a>
  <a id="798" class="Keyword">field</a>
    <a id="_≈_.head-≡"></a><a id="808" href="Streams.html#808" class="Field">head-≡</a> <a id="815" class="Symbol">:</a> <a id="817" href="Streams.html#258" class="Field">head</a> <a id="822" href="Streams.html#754" class="Bound">x</a> <a id="824" href="Agda.Builtin.Cubical.Path.html#272" class="Function Operator">≡</a> <a id="826" href="Streams.html#258" class="Field">head</a> <a id="831" href="Streams.html#756" class="Bound">y</a>
    <a id="_≈_.tail-≈"></a><a id="837" href="Streams.html#837" class="Field">tail-≈</a> <a id="844" class="Symbol">:</a> <a id="846" href="Streams.html#271" class="Field">tail</a> <a id="851" href="Streams.html#754" class="Bound">x</a> <a id="853" href="Streams.html#739" class="Record Operator">≈</a> <a id="855" href="Streams.html#271" class="Field">tail</a> <a id="860" href="Streams.html#756" class="Bound">y</a>
<a id="862" class="Keyword">open</a> <a id="867" href="Streams.html#739" class="Module Operator">_≈_</a>
</pre>
Okay, now we have a proof of coinductive extensionality!

<pre class="Agda"><a id="≈→≡"></a><a id="942" href="Streams.html#942" class="Function">≈→≡</a> <a id="946" class="Symbol">:</a> <a id="948" class="Symbol">∀</a> <a id="950" class="Symbol">{</a><a id="951" href="Streams.html#951" class="Bound">A</a> <a id="953" class="Symbol">:</a> <a id="955" href="Agda.Primitive.html#320" class="Primitive">Set</a><a id="958" class="Symbol">}</a> <a id="960" class="Symbol">→</a> <a id="962" class="Symbol">∀</a> <a id="964" class="Symbol">{</a><a id="965" href="Streams.html#965" class="Bound">xs</a> <a id="968" href="Streams.html#968" class="Bound">ys</a> <a id="971" class="Symbol">:</a> <a id="973" href="Streams.html#203" class="Record">Stream</a> <a id="980" href="Streams.html#951" class="Bound">A</a><a id="981" class="Symbol">}</a> <a id="983" class="Symbol">→</a> <a id="985" href="Streams.html#965" class="Bound">xs</a> <a id="988" href="Streams.html#739" class="Record Operator">≈</a> <a id="990" href="Streams.html#968" class="Bound">ys</a> <a id="993" class="Symbol">→</a> <a id="995" href="Streams.html#965" class="Bound">xs</a> <a id="998" href="Agda.Builtin.Cubical.Path.html#272" class="Function Operator">≡</a> <a id="1000" href="Streams.html#968" class="Bound">ys</a>
<a id="1003" href="Streams.html#258" class="Field">head</a> <a id="1008" class="Symbol">(</a><a id="1009" href="Streams.html#942" class="Function">≈→≡</a> <a id="1013" href="Streams.html#1013" class="Bound">xs≈ys</a> <a id="1019" href="Streams.html#1019" class="Bound">i</a><a id="1020" class="Symbol">)</a> <a id="1022" class="Symbol">=</a> <a id="1024" class="Symbol">(</a><a id="1025" href="Streams.html#808" class="Field">head-≡</a> <a id="1032" href="Streams.html#1013" class="Bound">xs≈ys</a><a id="1037" class="Symbol">)</a> <a id="1039" href="Streams.html#1019" class="Bound">i</a>
<a id="1041" href="Streams.html#271" class="Field">tail</a> <a id="1046" class="Symbol">(</a><a id="1047" href="Streams.html#942" class="Function">≈→≡</a> <a id="1051" href="Streams.html#1051" class="Bound">xs≈ys</a> <a id="1057" href="Streams.html#1057" class="Bound">i</a><a id="1058" class="Symbol">)</a> <a id="1060" class="Symbol">=</a> <a id="1062" href="Streams.html#942" class="Function">≈→≡</a> <a id="1066" class="Symbol">(</a><a id="1067" href="Streams.html#837" class="Field">tail-≈</a> <a id="1074" href="Streams.html#1051" class="Bound">xs≈ys</a><a id="1079" class="Symbol">)</a> <a id="1081" href="Streams.html#1057" class="Bound">i</a>

<a id="≡→≈"></a><a id="1084" href="Streams.html#1084" class="Function">≡→≈</a> <a id="1088" class="Symbol">:</a> <a id="1090" class="Symbol">∀</a> <a id="1092" class="Symbol">{</a><a id="1093" href="Streams.html#1093" class="Bound">A</a> <a id="1095" class="Symbol">:</a> <a id="1097" href="Agda.Primitive.html#320" class="Primitive">Set</a><a id="1100" class="Symbol">}</a> <a id="1102" class="Symbol">→</a> <a id="1104" class="Symbol">∀</a> <a id="1106" class="Symbol">{</a><a id="1107" href="Streams.html#1107" class="Bound">xs</a> <a id="1110" href="Streams.html#1110" class="Bound">ys</a> <a id="1113" class="Symbol">:</a> <a id="1115" href="Streams.html#203" class="Record">Stream</a> <a id="1122" href="Streams.html#1093" class="Bound">A</a><a id="1123" class="Symbol">}</a> <a id="1125" class="Symbol">→</a> <a id="1127" href="Streams.html#1107" class="Bound">xs</a> <a id="1130" href="Agda.Builtin.Cubical.Path.html#272" class="Function Operator">≡</a> <a id="1132" href="Streams.html#1110" class="Bound">ys</a> <a id="1135" class="Symbol">→</a> <a id="1137" href="Streams.html#1107" class="Bound">xs</a> <a id="1140" href="Streams.html#739" class="Record Operator">≈</a> <a id="1142" href="Streams.html#1110" class="Bound">ys</a>
<a id="1145" href="Streams.html#808" class="Field">head-≡</a> <a id="1152" class="Symbol">(</a><a id="1153" href="Streams.html#1084" class="Function">≡→≈</a> <a id="1157" href="Streams.html#1157" class="Bound">xs≡ys</a><a id="1162" class="Symbol">)</a> <a id="1164" class="Symbol">=</a> <a id="1166" class="Symbol">λ</a> <a id="1168" href="Streams.html#1168" class="Bound">i</a> <a id="1170" class="Symbol">→</a> <a id="1172" href="Streams.html#258" class="Field">head</a> <a id="1177" class="Symbol">(</a><a id="1178" href="Streams.html#1157" class="Bound">xs≡ys</a> <a id="1184" href="Streams.html#1168" class="Bound">i</a><a id="1185" class="Symbol">)</a>
<a id="1187" href="Streams.html#837" class="Field">tail-≈</a> <a id="1194" class="Symbol">(</a><a id="1195" href="Streams.html#1084" class="Function">≡→≈</a> <a id="1199" href="Streams.html#1199" class="Bound">xs≡ys</a><a id="1204" class="Symbol">)</a> <a id="1206" class="Symbol">=</a> <a id="1208" href="Streams.html#1084" class="Function">≡→≈</a> <a id="1212" class="Symbol">(λ</a> <a id="1215" href="Streams.html#1215" class="Bound">i</a> <a id="1217" class="Symbol">→</a> <a id="1219" href="Streams.html#271" class="Field">tail</a> <a id="1224" class="Symbol">(</a><a id="1225" href="Streams.html#1199" class="Bound">xs≡ys</a> <a id="1231" href="Streams.html#1215" class="Bound">i</a><a id="1232" class="Symbol">))</a>
</pre>
Now we must show our equation.

<pre class="Agda"><a id="refl"></a><a id="1280" href="Streams.html#1280" class="Function">refl</a> <a id="1285" class="Symbol">:</a> <a id="1287" class="Symbol">∀</a> <a id="1289" class="Symbol">{</a><a id="1290" href="Streams.html#1290" class="Bound">A</a> <a id="1292" class="Symbol">:</a> <a id="1294" href="Agda.Primitive.html#320" class="Primitive">Set</a><a id="1297" class="Symbol">}</a> <a id="1299" class="Symbol">→</a> <a id="1301" class="Symbol">∀</a> <a id="1303" class="Symbol">{</a><a id="1304" href="Streams.html#1304" class="Bound">x</a> <a id="1306" class="Symbol">:</a> <a id="1308" href="Streams.html#1290" class="Bound">A</a><a id="1309" class="Symbol">}</a> <a id="1311" class="Symbol">→</a> <a id="1313" href="Streams.html#1304" class="Bound">x</a> <a id="1315" href="Agda.Builtin.Cubical.Path.html#272" class="Function Operator">≡</a> <a id="1317" href="Streams.html#1304" class="Bound">x</a>
<a id="1319" href="Streams.html#1280" class="Function">refl</a> <a id="1324" class="Symbol">{</a><a id="1325" class="Argument">x</a> <a id="1327" class="Symbol">=</a> <a id="1329" href="Streams.html#1329" class="Bound">x</a><a id="1330" class="Symbol">}</a> <a id="1332" class="Symbol">=</a> <a id="1334" class="Symbol">λ</a> <a id="1336" href="Streams.html#1336" class="Bound">_</a> <a id="1338" class="Symbol">→</a> <a id="1340" href="Streams.html#1329" class="Bound">x</a>
<a id="1342" class="Symbol">{-#</a> <a id="1346" class="Keyword">INLINE</a> <a id="1353" href="Streams.html#1280" class="Function">refl</a> <a id="1358" class="Symbol">#-}</a>

<a id="evens∙tail≈odds"></a><a id="1363" href="Streams.html#1363" class="Function">evens∙tail≈odds</a> <a id="1379" class="Symbol">:</a> <a id="1381" class="Symbol">∀</a> <a id="1383" class="Symbol">{</a><a id="1384" href="Streams.html#1384" class="Bound">A</a> <a id="1386" class="Symbol">:</a> <a id="1388" href="Agda.Primitive.html#320" class="Primitive">Set</a><a id="1391" class="Symbol">}</a> <a id="1393" class="Symbol">→</a> <a id="1395" class="Symbol">∀</a> <a id="1397" class="Symbol">(</a><a id="1398" href="Streams.html#1398" class="Bound">xs</a> <a id="1401" class="Symbol">:</a> <a id="1403" href="Streams.html#203" class="Record">Stream</a> <a id="1410" href="Streams.html#1384" class="Bound">A</a><a id="1411" class="Symbol">)</a> <a id="1413" class="Symbol">→</a> <a id="1415" href="Streams.html#377" class="Function">evens</a> <a id="1421" class="Symbol">(</a><a id="1422" href="Streams.html#271" class="Field">tail</a> <a id="1427" href="Streams.html#1398" class="Bound">xs</a><a id="1429" class="Symbol">)</a> <a id="1431" href="Streams.html#739" class="Record Operator">≈</a> <a id="1433" href="Streams.html#560" class="Function">odds</a> <a id="1438" href="Streams.html#1398" class="Bound">xs</a>
<a id="1441" href="Streams.html#808" class="Field">head-≡</a> <a id="1448" class="Symbol">(</a><a id="1449" href="Streams.html#1363" class="Function">evens∙tail≈odds</a> <a id="1465" href="Streams.html#1465" class="Bound">xs</a><a id="1467" class="Symbol">)</a> <a id="1469" class="Symbol">=</a> <a id="1471" href="Streams.html#1280" class="Function">refl</a>
<a id="1476" href="Streams.html#837" class="Field">tail-≈</a> <a id="1483" class="Symbol">(</a><a id="1484" href="Streams.html#1363" class="Function">evens∙tail≈odds</a> <a id="1500" href="Streams.html#1500" class="Bound">xs</a><a id="1502" class="Symbol">)</a> <a id="1504" class="Symbol">=</a> <a id="1506" href="Streams.html#1084" class="Function">≡→≈</a> <a id="1510" href="Streams.html#1280" class="Function">refl</a>

<a id="evens∙tail≡odds"></a><a id="1516" href="Streams.html#1516" class="Function">evens∙tail≡odds</a> <a id="1532" class="Symbol">:</a> <a id="1534" class="Symbol">∀</a> <a id="1536" class="Symbol">{</a><a id="1537" href="Streams.html#1537" class="Bound">A</a> <a id="1539" class="Symbol">:</a> <a id="1541" href="Agda.Primitive.html#320" class="Primitive">Set</a><a id="1544" class="Symbol">}</a> <a id="1546" class="Symbol">→</a> <a id="1548" class="Symbol">∀</a> <a id="1550" class="Symbol">(</a><a id="1551" href="Streams.html#1551" class="Bound">xs</a> <a id="1554" class="Symbol">:</a> <a id="1556" href="Streams.html#203" class="Record">Stream</a> <a id="1563" href="Streams.html#1537" class="Bound">A</a><a id="1564" class="Symbol">)</a> <a id="1566" class="Symbol">→</a> <a id="1568" href="Streams.html#377" class="Function">evens</a> <a id="1574" class="Symbol">(</a><a id="1575" href="Streams.html#271" class="Field">tail</a> <a id="1580" href="Streams.html#1551" class="Bound">xs</a><a id="1582" class="Symbol">)</a> <a id="1584" href="Agda.Builtin.Cubical.Path.html#272" class="Function Operator">≡</a> <a id="1586" href="Streams.html#560" class="Function">odds</a> <a id="1591" href="Streams.html#1551" class="Bound">xs</a>
<a id="1594" href="Streams.html#1516" class="Function">evens∙tail≡odds</a> <a id="1610" href="Streams.html#1610" class="Bound">xs</a> <a id="1613" class="Symbol">=</a> <a id="1615" href="Streams.html#942" class="Function">≈→≡</a> <a id="1619" class="Symbol">(</a><a id="1620" href="Streams.html#1363" class="Function">evens∙tail≈odds</a> <a id="1636" href="Streams.html#1610" class="Bound">xs</a><a id="1638" class="Symbol">)</a>
</pre>